export const AFFIRMATIONS = [
  'You are magnetic and people genuinely enjoy your company.',
  'Every conversation you start builds your confidence.',
  'You belong in every room you walk into.',
  'Your presence is a gift to those around you.',
  'You connect with others easily and authentically.',
  'Social situations are opportunities for you to shine.',
  'You are becoming more confident with every interaction.',
  'People are drawn to your warmth and authenticity.',
  'You handle social situations with grace and ease.',
  'Your unique perspective makes conversations richer.',
  'You are worthy of deep, meaningful connections.',
  'Every small step you take builds your social power.',
  'You have the courage to initiate conversations.',
  'You are growing stronger and bolder every day.',
  'Rejection cannot dim your light. You keep going.',
  'You radiate confidence even when you feel nervous.',
  'You are exactly the kind of person others want to know.',
  'Your voice deserves to be heard in any room.',
  'You turn strangers into friends effortlessly.',
  'Social anxiety does not define you. Courage does.',
  'You surprise yourself with how capable you really are.',
  'Every challenge you complete makes the next one easier.',
  'You are building a social life that energizes you.',
  'You speak up, and people listen and respect you.',
  'You are on your way to becoming unstoppably confident.',
];
